---
title: "EDLD610 Winter19 Lab1"
author: Jeongim, Ting-fen, Teresa
output: 
  html_document:
    toc: true
    toc_float: true
---




```{r setup, include = FALSE}

library("tidyverse")
library("rio")
library("here")
library("knitr")
library("lubridate")
knitr::opts_chunk$set(warning = FALSE,
                      message = FALSE,
                      error = TRUE,
                      fig.width = 6.5,
                      fig.height = 8
                      )


```

# Commit 1
```{r load_data}
df <- import(here::here("data", "rstats_tweets.rds"),
             setclass = "tbl_df")

# head(df, n = 10)

```


# Commit 2
```{r commit2}

subset <- df %>%
  count(screen_name) %>%
  arrange(desc(n)) %>%
  slice (1:25)

#str(subset)

subset %>%
  mutate(screen_name = as.factor(screen_name),
         screen_name = forcats::fct_reorder(screen_name, n)) %>%
  ggplot(aes(x = screen_name, y = n)) + 
  geom_col() +
  coord_flip()

# str(subset)

```


# Commit 3
```{r commit3,fig.width = 10,fig.height = 10}


subset <- df %>%
  count(screen_name) %>%
  arrange(desc(n)) %>%
  slice (1:25)

#str(subset)


subset %>%
  mutate(screen_name = as.factor(screen_name),
         screen_name = forcats::fct_reorder(screen_name, n)) %>%
  ggplot(aes(x = screen_name, y = n)) + 
  geom_col(fill = "cornflowerblue") +
  coord_flip() +
  labs(title = "Most prolific #rstats tweeters",
       subtitle = "Top 25 screen names displayed",
       x = "Twitter Screen Name",
       y = "Count
            Data from Mike Kearny, distrubted via #tidytuesday") +
  theme_minimal(base_size = 11)


```


# Commit 4
```{r commit4 }


subset4 <- df %>% 
  mutate(month = lubridate::round_date(created_at, unit = "month")) %>% 
  filter(month < lubridate::as_datetime("2019-01-01 00:00:00")) %>% 
  count(month) %>% 
  arrange(month)

# View(subset4)

subset4 %>% 
ggplot(aes(x = month, y = n)) +
  geom_line() +
  geom_smooth() 
  

```


# Commit 5
```{r commit5, fig.width=10, fig.height=10}
subset4 %>% 
ggplot(aes(x = month, y = n)) +
  geom_line(color = "gray40",
            size = 2) +
  geom_smooth(method = "auto",
              se = FALSE,
              color = "magenta",
              size = 2) +
  theme_minimal(base_size = 20) +
  geom_area(alpha = 0.3, fill = "cornflowerblue") +
  labs(title = "Growth of the #rstats hashtag on twitter over time", 
       x = "Year(data summarized by month)",
       y = "Number of #rstats tweets",
       caption = "Data from Mike Kearny, distributed via #tidytuesday")


```

